- hosts: localhost
  gather_facts: no
  tasks:
    - name: Load default values
      include_vars:
        file: pipeline/values.yml
        name: default_values

    - name: Load production values
      include_vars:
        file: pipeline/values-prod.yml
        name: prod_values

    - name: Merge values
      set_fact:
        merged_values: "{{ default_values | combine(prod_values, recursive=True) }}"

    - name: Write merged values to file
      copy:
        dest: values.yml
        content: "{{ merged_values | to_nice_yaml }}"
        force: yes
